name: sane
channels:
  - conda-forge

dependencies:
  - python=3.12

  # Notebooks and IPython
  - jupyterlab
  - notebook
  - ipython
  - jupyter

  # Data handling
  - dask
  - openpyxl
  - scipy
  - pandas
  - pyreadstat
  - numpy
  - polars
  - pyarrow
  - jupysql
  - duckdb
  - duckdb-engine
  - arrow               
  - python-dateutil    

  # Visualization
  - plotly
  - matplotlib
  - geopandas
  - shapely
  - fiona
  - cartopy
  - folium
  - gdal
  - geojson
  - pyproj
  - seaborn
  - hvplot
  - bokeh            
  - altair           
  - panel      
  - python-kaleido

  # Networks
  - networkx
  - igraph

  # ML and interpretability
  - scikit-learn
  - lime
  - eli5
  - shap
  - imbalanced-learn
  - interpret
  - optuna
  - xgboost           
  - lightgbm          
  - catboost          
  - joblib            
  - mlflow            
  - dowhy
  - causalml 
  - causal-learn
  - pgmpy 
  - pymc
  - numpyro
  - blackjax 
  - nutpie

  # NLP and text
  - nltk              
  - spacy             

  # SQL / DB Interface
  - sqlalchemy        

  # Data validation and config
  - pandera           
  - pydantic          

  # Parallel / performance
  - multiprocess      
  - threadpoolctl     

  # File/HTML/PDF parsing 
  - beautifulsoup4    
  - lxml              

  # Pip-only packages
  - pip
  - pip:
      - metasyn  # synthetic data
